server:
  port: 8000

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhsot:8761/eureka

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://localhost:8081/order-service/**
          predicates: # 조건절
            - Path=/order-service/**
          filters:
#            - AddRequestHeader=order-request, order-request-header2
#            - AddResponseHeader=order-response, order-response-header2
            - CustomFilter
        - id: user-service
          uri: http://localhost:8082/user-service/**
          predicates:
            - Path=/user-service/**
          filters:
#            - AddRequestHeader=user-request, user-request-header2
#            - AddResponseHeader=user-response, user-response-header2
            - CustomFilter
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
